name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  build-with-nix:
    name: build ${{ matrix.pkg }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - aderyn
          - foundry-zksync
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Build Packages
        run: nix build .#${{ matrix.pkg }}
