name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  build-with-nix:
    name: build ${{ matrix.pkg }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - aderyn
          # wired bug
          # - foundry-zksync
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Setup Attic
        run: |
          nix profile install 'nixpkgs#attic-client'
          attic login central ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          attic use central:${{ secrets.ATTIC_CACHE }}

      - name: Build Packages
        run: nix build --no-sandbox .#${{ matrix.pkg }}

      - name: Push to Attic
        if: success()
        run: attic push central:${{ secrets.ATTIC_CACHE }} ./result
